import { z } from "zod";

// --- Product Schemas ---

export const createProductSchema = z.object({
  name: z.string().min(1, "Name is required").max(255, "Name too long"),
  // SKU is now auto-generated by the backend from category/name prefix + sequence number.
  // If provided, it will be used as-is (for backward compatibility or manual override).
  sku: z
    .string()
    .max(100, "SKU too long")
    .regex(/^[A-Z0-9-]+$/, "SKU must be uppercase letters, digits, and dashes only")
    .optional(),
  description: z.string().max(1000, "Description too long").optional(),
  category: z.string().max(100, "Category too long").optional(),
  price: z.number().positive("Price must be greater than 0"),
  reorderLevel: z.number().int("Reorder level must be an integer").min(0, "Reorder level cannot be negative").default(10),
  // Opening stock: optional quantity to set when creating a product.
  // If > 0, a "received" movement is auto-created with reason "Opening stock".
  initialStock: z.number().int("Initial stock must be an integer").min(0, "Initial stock cannot be negative").default(0),
});

export const updateProductSchema = z.object({
  name: z.string().min(1, "Name is required").max(255, "Name too long").optional(),
  description: z.string().max(1000, "Description too long").optional(),
  category: z.string().max(100, "Category too long").optional(),
  price: z.number().positive("Price must be greater than 0").optional(),
  reorderLevel: z.number().int("Reorder level must be an integer").min(0, "Reorder level cannot be negative").optional(),
});

// --- Stock Adjustment Schema ---

export const movementTypeEnum = z.enum(["received", "sold", "returned", "adjustment", "damaged"]);

export const adjustStockSchema = z.object({
  quantity: z.number().int("Quantity must be an integer").refine((val) => val !== 0, "Quantity cannot be zero"),
  movementType: movementTypeEnum,
  reason: z.string().max(500, "Reason too long").optional(),
});

// --- Query Parameter Schemas ---

export const productQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  category: z.string().optional(),
  status: z.enum(["all", "active", "discontinued"]).default("all"),
  stockLevel: z.enum(["all", "low", "out"]).default("all"),
  search: z.string().optional(),
});

export const movementQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  productId: z.string().uuid().optional(),
  movementType: movementTypeEnum.optional(),
});

// --- Settings/Invitation Schemas ---

const roleEnum = z.enum(["admin", "manager", "member"]);

export const inviteMemberSchema = z.object({
  email: z.string().email("Invalid email address").max(255, "Email too long"),
  role: roleEnum,
});

export const changeRoleSchema = z.object({
  role: roleEnum,
});

// --- Type exports ---

export type CreateProductInput = z.infer<typeof createProductSchema>;
export type UpdateProductInput = z.infer<typeof updateProductSchema>;
export type AdjustStockInput = z.infer<typeof adjustStockSchema>;
export type ProductQuery = z.infer<typeof productQuerySchema>;
export type MovementQuery = z.infer<typeof movementQuerySchema>;
export type InviteMemberInput = z.infer<typeof inviteMemberSchema>;
export type ChangeRoleInput = z.infer<typeof changeRoleSchema>;
