// Product as returned by the backend
export interface Product {
  id: string;
  organizationId: string;
  name: string;
  sku: string;
  description: string | null;
  category: string | null;
  price: string; // numeric comes as string from PostgreSQL
  currentStock: number;
  reorderLevel: number;
  status: "active" | "discontinued";
  aiRecommendation: string | null;
  aiReasoning: string | null;
  aiAnalyzedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

// Product with recent movements attached (GET /products/:id response)
export interface ProductWithMovements extends Product {
  recentMovements: StockMovement[];
}

// Stock movement record
export interface StockMovement {
  id: string;
  organizationId: string;
  productId: string;
  movementType: "received" | "sold" | "returned" | "adjustment" | "damaged";
  quantity: number;
  reason: string | null;
  stockBefore: number;
  stockAfter: number;
  createdBy: string | null;
  createdAt: string;
}

// Create product input — matches backend Zod schema
export interface CreateProductInput {
  name: string;
  sku?: string; // Optional — auto-generated by backend if not provided
  description?: string;
  category?: string;
  price: number;
  reorderLevel?: number;
  initialStock?: number; // Optional opening stock quantity
}

// Update product input — matches backend Zod schema
export interface UpdateProductInput {
  name?: string;
  description?: string;
  category?: string;
  price?: number;
  reorderLevel?: number;
}

// Stock adjustment input — matches backend Zod schema
export interface StockAdjustInput {
  quantity: number;
  movementType: "received" | "sold" | "returned" | "adjustment" | "damaged";
  reason?: string;
}

// Paginated response from backend
export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
}

// Dashboard stats from GET /products/stats
export interface ProductStats {
  totalProducts: number;
  lowStockCount: number;
  outOfStockCount: number;
  totalInventoryValue: number;
}

// Filter state for product list
export interface ProductFilters {
  search: string;
  category: string;
  status: "all" | "active" | "discontinued";
  stockLevel: "all" | "low" | "out";
}

// Auth session from BetterAuth GET /api/auth/get-session
export interface AuthSession {
  session: {
    id: string;
    userId: string;
    activeOrganizationId: string | null;
    expiresAt: string;
  };
  user: {
    id: string;
    name: string;
    email: string;
    image: string | null;
  };
}

// Organization from BetterAuth
export interface Organization {
  id: string;
  name: string;
  slug: string;
  logo: string | null;
  createdAt: string;
}
